/**/*:
  ros__parameters:
    ll2_map_server_name: /localization/lanelet2_map_server
    lanelet_match_max_distance_m: 0.5
    lanelet_match_max_yaw_diff_rad: 1.047197551
    prediction_horizon_s: 5.0
    prediction_sample_interval_s: 0.5
    centerline_convergence_distance_m: 10.0
    max_lateral_acceleration_mps2: 2.5
    max_longitudinal_deceleration_mps2: 2.0
    max_longitudinal_acceleration_mps2: 1.0
    infeasible_hypothesis_probability: 0.01
    yield_prediction_enabled: true
    yield_stop_margin_m: 0.5
    yield_clearance_time_s: 1.0
    ego_data_timeout_s: 1.0
    unmatched_object_prediction_mode: kinematic
