/**/*:
  ros__parameters:
    ll2_map_server_name: datasets
    lanelet_match_max_distance_m: 0.5
    lanelet_match_max_yaw_diff_rad: 1.047197551
    prediction_horizon_s: 5.0
    prediction_sample_interval_s: 0.5
    unmatched_object_prediction_mode: kinematic
