<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">

  <name>lanelet2_object_list_prediction</name>
  <version>1.0.0</version>
  <description>Predicts object movements via Lanelet2 map information</description>

  <maintainer email="jean-pierre.busch@ika.rwth-aachen.de">Jean-Pierre Busch</maintainer>
  <author email="jean-pierre.busch@ika.rwth-aachen.de">Jean-Pierre Busch</author>
  <author email="silas.damaschke@ika.rwth-aachen.de">Silas Damaschke</author>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>lanelet2_core</depend>
  <depend>lanelet2_map_interface</depend>
  <depend>lanelet2_routing</depend>
  <depend>lanelet2_traffic_rules</depend>
  <depend>perception_msgs</depend>
  <depend>perception_msgs_utils</depend>
  <depend>rclcpp</depend>
  <depend>tf2</depend>
  <depend>tf2_perception_msgs</depend>
  <depend>tf2_ros</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_cmake_clang_format</test_depend>
  <test_depend>ament_cmake_clang_tidy</test_depend>
  <test_depend>ament_cmake_flake8</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
